print("Getting to know you!")

name = input("What is your name?: ")
print("Hello " + name + "!")
food = input("What is your favorite food?: ")
print("I like " + food + " too!")
music = input("What is your favorite music?: ")
print("I like " + music + " too!")
live = input("Where do you live?: ")
print("I live in " + live + " too!")
print("You are " + name + ".")
print("You're probably hungry for " + food + ".")
print("You're probably listening to " + music + ".")
print("You're probably living in the amazing " + live + ".")
